config/routes.rb
Rails.application.routes.draw do
    
#  devise_for :users
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'front#index'
  
  get '/dashboard' => 'dashboard#index'
  get '/email/new' => 'email#new'
  post '/email/create' => "email#create", :as => :create_email
  
  resources :email_templates
  

end

app/models/email_template.rb
class EmailTemplate < ActiveRecord::Base
  
  belongs_to :user
  
  validates(:name, { presence: true, uniqueness: true })
  validates(:body, { presence: true })
  validates(:subject, { presence: true })
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :email_templates
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates(:email,{ presence: true, uniqueness: true})
  validates(:name,{ presence: true, uniqueness: true })
  validates( :password,{ presence: true,length: { minimum: 8 }, :on => :create })

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    dashboard_path
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_action :validates_user
  
  def index
  end

  private 

  def validates_user
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "You need to be signed in!"
    end
  end
  
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  
  before_action :validates_user
  
  def new
    begin
      @template = current_user.email_templates.find(params[:template])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to email_templates_path
    end
  end
  
  def create
    begin  
    if params[:file] #if there is a file to send
      EmailMailer.new_email(current_user,params[:to],params[:subject],params[:body],params[:file].read(),params[:file].original_filename).deliver
    else
      EmailMailer.new_email(current_user,params[:to],params[:subject],params[:body]).deliver
    end
      redirect_to email_templates_path, notice: "Your email has been sent succesfully!"
    rescue Net::ReadTimeout => e
      redirect_to email_templates_path, alert: "Sending time was exceeded, your email could not be sent, Please try again!"
    rescue Net::SMTPFatalError => e
      redirect_to email_templates_path, alert: "Recipient address invalid, your email could not be sent, Please try again!"
    rescue Net::SMTPServerBusy => e
      redirect_to email_templates_path, alert: "Email server is busy, your email could not be sent, Please try again!"
    end
  end
  
  private
  
  def validates_user
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "You need to be signed in!"
    end
  end
  
end

app/controllers/email_templates_controller.rb
class EmailTemplatesController < ApplicationController
  before_action :validates_user
  before_action :set_email_template, only: [:show, :destroy, :edit, :update]
  
  def index
    @email_template = current_user.email_templates.order(name: :asc).all
    
  end
  
  def show
  
  end
  
  def new 
    @email_template = EmailTemplate.new
  end
  
  def edit
    
  end
  
  def update
    if @email_template.update(email_template_params)
      redirect_to @email_template, notice: "Your template has been updated!"
    else
      render :edit
    end
  end
  
  def create
    
    @email_template = current_user.email_templates.new(email_template_params)
  
    if @email_template.save
      redirect_to @email_template
    else
      render :new
    end
    
  end

  def destroy
    @email_template.destroy
    redirect_to email_templates_path, notice: "Your template has been deleted!"	
  end
  
  # Private methods
  private 
  
  def set_email_template
    begin
      @email_template = current_user.email_templates.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to email_templates_path
    end
    
  end
  
  def email_template_params
    params.require(:email_template).permit(:name,:body,:subject)
  end
  
  def validates_user
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "You need to be signed in!"
    end
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
    def index   
         
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/email_templates_helper.rb
module EmailTemplatesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/views/dashboard/index.html.erb
<div class="m-panel">

  <div class="m-panel-header">
    <h3>Dashboard</h3>
  </div>
  <div class="m-panel-content">
    <div class="lateral-menu">
      <ul>
        <li><%= link_to "My templates", email_templates_path %></li>  
        <li><%= link_to "Edit or cancel my user account", edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>  
      </ul>
    </div>
  </div>
</div>

app/views/email_templates/_form.html.erb
<div class="m-panel">
  <div class="m-panel-header"><h3><%= title %></h3></div>
  <div class="m-panel-content">
    <%= form_for(@email_template) do |f| %>

    <% @email_template.errors.full_messages.each { |error| %>
    <div class="alert">
      <%= error %>
    </div>

    <% } %>

    <label>Template name</label>
    <%= f.text_field(:name, autofocus: true, required: true) %>

    <label class= "form-label">Template subject</label>
    <%= f.text_field(:subject, required: true) %>
     
    <label class= "form-label">Template body</label>
    <%= f.text_area(:body, rows: 8, required: true) %>

    <%= f.submit "Save"%>
    <% end %>
  </div>
</div>

app/views/email_templates/edit.html.erb
<%= link_to "Back", email_templates_path, class: "back" %>
<%= render "form", title: "Editing template" %>

app/views/email_templates/index.html.erb
<%= link_to "Back", dashboard_path, class: "back" %>
<div style="text-align:center">
<%= link_to "+ Create a new template", new_email_template_path, class: "new-template"  %>
</div>

<div class="m-panel">
  <div class="m-panel-header">
    <h3>My Templates</h3>    
  </div>
  <div class="m-panel-content">
    <div class="search">
      <input id="search-template" type="text" placeholder="Write the template name...">
    </div>
    
    <% @email_template.each do |template| %>
    <div class="template-container">
      <h3><%= template.name %></h3>
      <%= link_to "Create email", email_new_path(template: template.id), class: "create_email" %>
      <%= link_to "View", email_template_path(template), class: "see" %>
      <%= link_to "Delete", template, class: "delete", method: :delete %>
      <%= link_to "Edit", edit_email_template_path(template), class: "edit" %>
    </div>
    
    <% end %>
  </div>
</div>

app/views/email_templates/new.html.erb
<%= link_to "Back", email_templates_path, class: "back" %>
<%= render "form", title: "New template" %>

app/views/email_templates/show.html.erb
<%= link_to "Back", email_templates_path, class: "back" %>

<div class="m-panel">
  <div class="m-panel-header">
    <h3><%= @email_template.name %></h3>
  </div>
  <div class="m-panel-content">
    <div class="template-container" style="text-align:left!important; color:#ccc">
      <p><b>Subject:</b> <%= @email_template.subject %></p><br>
      <p><b>Body:</b> <%= @email_template.body %></p>
      <div style="text-align:right">
        <%= link_to "Edit", edit_email_template_path(@email_template), class: "edit" %>
        <%= link_to "Delete", @email_template, class: "delete", method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/front/index.html.erb
<%= image_tag("front.png", class: "front-img")%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class="nav-container">
        <span class="logo">
            <%= link_to "Email Marketing", root_path %>
        </span>
        <span class="btn-nav-bar">
            <span></span>
            <span></span>
            <span></span>
        </span>
        <nav class="nav-bar">
            <ul class="">
                <li><%= link_to "Home", root_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to "Dashboard", dashboard_path %> </li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
              <% else %>
              <li><%= link_to "Sign in", user_session_path %> </li>
              <li><%= link_to "Sign up", new_user_registration_path %> </li>
              <% end %>
            </ul>
        </nav>
    </header>
    <div class="content">
        <% if user_signed_in? %>
          <div class="username"><b>User: </b><%= current_user.name%></div>
        <% end %>
        
        <div class="devise-alert">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
        <footer>Created by Melvin Rodriguez Rodriguez.</footer>
    </div>
</body>
</html>